---

dist: xenial
cache:
  directories:
    - $HOME/.cache/pip

sudo: required

services:
  - docker

language: python

install:
  - pip install poetry tox

jobs:
  include:
    - stage: lint
      python: 3.8
      env:
        - TOXENV=lint
      script:
        - tox

    - stage: test
      python: 3.7
      env:
        - TOXENV=py37
      script:
        - tox
    - stage: test
      python: 3.8
      env:
        - TOXENV=py38
      script:
        - tox
